# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{htmldoc-rails}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Elliot Winkler"]
  s.date = %q{2010-02-11}
  s.description = %q{Generate PDFs from your Rails views using HTMLDoc}
  s.email = %q{elliot.winkler@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "init.rb",
     "lib/htmldoc-rails.rb",
     "lib/htmldoc_rails.rb",
     "lib/htmldoc_rails/controller.rb",
     "lib/htmldoc_rails/htmldoc_ext.rb",
     "lib/htmldoc_rails/version.rb",
     "test/all.rb",
     "test/helper.rb",
     "test/rails_template_process.txt",
     "test/test_render_pdf.rb",
     "test/test_render_pdf_to_file.rb",
     "test/tmp/out.html",
     "test/tmp/out.pdf",
     "test/views/render_pdf/_foo.html.erb",
     "test/views/render_pdf/doc.html.erb",
     "test/views/render_pdf/doc.rpdf",
     "test/views/render_pdf/doc_with_partial.html.erb",
     "test/views/render_pdf/no_arguments.html.erb",
     "test/views/render_pdf_to_file/_foo.html.erb",
     "test/views/render_pdf_to_file/doc.html.erb",
     "test/views/render_pdf_to_file/doc_with_partial.html.erb",
     "test/views/render_pdf_to_file/no_arguments.html.erb"
  ]
  s.homepage = %q{http://github.com/mcmire/htmldoc-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Generate PDFs from your Rails views using HTMLDoc}
  s.test_files = [
    "test/all.rb",
     "test/helper.rb",
     "test/test_render_pdf.rb",
     "test/test_render_pdf_to_file.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<htmldoc>, [">= 0"])
      s.add_runtime_dependency(%q<actionpack>, ["< 3.0"])
      s.add_development_dependency(%q<mcmire-protest>, [">= 0"])
      s.add_development_dependency(%q<mcmire-matchy>, [">= 0"])
      s.add_development_dependency(%q<mcmire-mocha>, [">= 0"])
      s.add_development_dependency(%q<mocha-protest-integration>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<htmldoc>, [">= 0"])
      s.add_dependency(%q<actionpack>, ["< 3.0"])
      s.add_dependency(%q<mcmire-protest>, [">= 0"])
      s.add_dependency(%q<mcmire-matchy>, [">= 0"])
      s.add_dependency(%q<mcmire-mocha>, [">= 0"])
      s.add_dependency(%q<mocha-protest-integration>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<htmldoc>, [">= 0"])
    s.add_dependency(%q<actionpack>, ["< 3.0"])
    s.add_dependency(%q<mcmire-protest>, [">= 0"])
    s.add_dependency(%q<mcmire-matchy>, [">= 0"])
    s.add_dependency(%q<mcmire-mocha>, [">= 0"])
    s.add_dependency(%q<mocha-protest-integration>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

